// Seed the AgentDoor directory with 200+ additional real services (batch 2)
// Usage: node seed2.mjs
// Avoids all services already registered in seed.mjs

const REGISTER_URL = "https://api.agentdoor.ai/register";

const services = [
  // ─── 1. Weather & Geo ───────────────────────────────────────────────
  { serviceName: "openweathermap", description: "Weather data API with current, forecast, and historical conditions", endpoint: "https://api.openweathermap.org/data/3.0", protocol: "REST", capabilities: "current weather, forecasts, alerts, air pollution, geocoding", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://openweathermap.org/api", authUrl: "https://home.openweathermap.org/users/sign_up", statusUrl: "https://status.openweather.com", contactUrl: "https://openweathermap.org/contact-us" },
  { serviceName: "weatherapi", description: "Real-time and forecast weather data for any location worldwide", endpoint: "https://api.weatherapi.com/v1", protocol: "REST", capabilities: "current weather, forecasts, astronomy, time zone, sports", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.weatherapi.com/docs/", authUrl: "https://www.weatherapi.com/signup.aspx", contactUrl: "https://www.weatherapi.com/contact.aspx" },
  { serviceName: "mapbox", description: "Maps, navigation, and location search APIs for developers", endpoint: "https://api.mapbox.com", protocol: "REST", capabilities: "maps, geocoding, directions, navigation, isochrones, tilesets", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.mapbox.com/api/", authUrl: "https://account.mapbox.com/auth/signup/", contactUrl: "https://www.mapbox.com/contact/sales" },
  { serviceName: "here-maps", description: "Location platform with mapping, routing, and geocoding services", endpoint: "https://geocode.search.hereapi.com/v1", protocol: "REST", capabilities: "maps, routing, geocoding, transit, fleet telematics, positioning", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.here.com/documentation", authUrl: "https://platform.here.com/sign-up", contactUrl: "https://www.here.com/contact" },
  { serviceName: "tomtom", description: "Location technology for maps, routing, and traffic data", endpoint: "https://api.tomtom.com", protocol: "REST", capabilities: "maps, search, routing, traffic, geofencing, EV charging", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.tomtom.com/", authUrl: "https://developer.tomtom.com/user/register", contactUrl: "https://developer.tomtom.com/support" },
  { serviceName: "ipinfo", description: "IP address geolocation and data enrichment API", endpoint: "https://ipinfo.io", protocol: "REST", capabilities: "IP geolocation, ASN, company, carrier, privacy detection", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://ipinfo.io/developers", authUrl: "https://ipinfo.io/signup", contactUrl: "https://ipinfo.io/contact" },
  { serviceName: "maxmind-geoip", description: "IP geolocation and fraud detection databases", endpoint: "https://geoip.maxmind.com/geoip/v2.1", protocol: "REST", capabilities: "IP geolocation, city lookup, ISP detection, fraud scoring", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://dev.maxmind.com/geoip", authUrl: "https://www.maxmind.com/en/account/login", contactUrl: "https://www.maxmind.com/en/company/contact-us" },
  { serviceName: "what3words", description: "Global addressing system dividing the world into 3m squares", endpoint: "https://api.what3words.com/v3", protocol: "REST", capabilities: "convert to/from 3 word addresses, autosuggest, grid section", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.what3words.com/public-api", authUrl: "https://accounts.what3words.com/register", contactUrl: "https://what3words.com/contact-us" },
  { serviceName: "geocodio", description: "US and Canadian geocoding and reverse geocoding service", endpoint: "https://api.geocod.io/v1.7", protocol: "REST", capabilities: "geocoding, reverse geocoding, batch processing, census data", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.geocod.io/docs/", authUrl: "https://dash.geocod.io/register", contactUrl: "https://www.geocod.io/contact/" },
  { serviceName: "locationiq", description: "Geocoding, routing, and mapping APIs built on OpenStreetMap", endpoint: "https://us1.locationiq.com/v1", protocol: "REST", capabilities: "geocoding, reverse geocoding, autocomplete, routing, static maps", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://locationiq.com/docs", authUrl: "https://my.locationiq.com/register", contactUrl: "https://locationiq.com/contact" },

  // ─── 2. Communication ──────────────────────────────────────────────
  { serviceName: "telegram-bot-api", description: "Bot API for building conversational bots on Telegram", endpoint: "https://api.telegram.org/bot", protocol: "REST", capabilities: "messaging, inline queries, payments, games, stickers, groups", pricingModel: "free", authMethod: "API key", docsUrl: "https://core.telegram.org/bots/api", authUrl: "https://t.me/BotFather", contactUrl: "https://telegram.org/support" },
  { serviceName: "whatsapp-business", description: "WhatsApp messaging API for businesses via Meta Cloud", endpoint: "https://graph.facebook.com/v18.0", protocol: "REST", capabilities: "messaging, templates, media, interactive messages, webhooks", pricingModel: "per-request", authMethod: "Bearer token", docsUrl: "https://developers.facebook.com/docs/whatsapp/cloud-api", authUrl: "https://developers.facebook.com/apps/", contactUrl: "https://www.facebook.com/business/help" },
  { serviceName: "zoom-api", description: "Video conferencing and collaboration platform API", endpoint: "https://api.zoom.us/v2", protocol: "REST", capabilities: "meetings, webinars, recordings, chat, phone, reports", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://developers.zoom.us/docs/api/", authUrl: "https://marketplace.zoom.us/develop/create", contactUrl: "https://support.zoom.us/hc/en-us" },
  { serviceName: "microsoft-teams", description: "Collaboration and communication APIs via Microsoft Graph", endpoint: "https://graph.microsoft.com/v1.0", protocol: "REST", capabilities: "teams, channels, chat, meetings, calls, presence", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://learn.microsoft.com/en-us/graph/teams-concept-overview", authUrl: "https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps", contactUrl: "https://developer.microsoft.com/en-us/graph/support" },
  { serviceName: "intercom", description: "Customer messaging platform with bots and help desk", endpoint: "https://api.intercom.io", protocol: "REST", capabilities: "messaging, inbox, bots, help center, product tours, surveys", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://developers.intercom.com/docs", authUrl: "https://app.intercom.com/a/developer-signup", contactUrl: "https://www.intercom.com/help" },
  { serviceName: "drift", description: "Conversational marketing and sales platform", endpoint: "https://driftapi.com", protocol: "REST", capabilities: "conversations, contacts, meetings, bots, playbooks", pricingModel: "subscription", authMethod: "OAuth2", docsUrl: "https://devdocs.drift.com/docs", authUrl: "https://dev.drift.com/apps", contactUrl: "https://www.drift.com/contact-us/" },
  { serviceName: "crisp", description: "Customer messaging platform with live chat and CRM", endpoint: "https://api.crisp.chat/v1", protocol: "REST", capabilities: "live chat, chatbots, CRM, campaigns, knowledge base, status page", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://docs.crisp.chat/api/v1/", authUrl: "https://app.crisp.chat/initiate/signup/", contactUrl: "https://crisp.chat/en/contact/" },
  { serviceName: "tawk-to", description: "Free live chat application for website customer support", endpoint: "https://api.tawk.to/v1", protocol: "REST", capabilities: "live chat, ticketing, knowledge base, video chat, chat pages", pricingModel: "free", authMethod: "API key", docsUrl: "https://developer.tawk.to/", authUrl: "https://www.tawk.to/sign-up/", contactUrl: "https://www.tawk.to/contact-us/" },
  { serviceName: "stream-chat", description: "Scalable chat API and messaging SDK for apps", endpoint: "https://chat.stream-io-api.com/api/v1.0", protocol: "REST", capabilities: "messaging, threads, reactions, moderation, push notifications", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://getstream.io/chat/docs/", authUrl: "https://getstream.io/try-for-free/", contactUrl: "https://getstream.io/contact/" },
  { serviceName: "sendbird", description: "Chat, voice, and video APIs for in-app communication", endpoint: "https://api-{app_id}.sendbird.com/v3", protocol: "REST", capabilities: "chat, group channels, moderation, push, announcements, bots", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://sendbird.com/docs/chat", authUrl: "https://dashboard.sendbird.com/auth/signup", contactUrl: "https://sendbird.com/contact-us" },

  // ─── 3. E-commerce ─────────────────────────────────────────────────
  { serviceName: "woocommerce", description: "Open-source e-commerce REST API for WordPress stores", endpoint: "https://{store}.com/wp-json/wc/v3", protocol: "REST", capabilities: "products, orders, customers, coupons, reports, webhooks", pricingModel: "free", authMethod: "API key", docsUrl: "https://woocommerce.github.io/woocommerce-rest-api-docs/", authUrl: "https://woocommerce.com/my-account/", contactUrl: "https://woocommerce.com/contact-us/" },
  { serviceName: "bigcommerce", description: "E-commerce platform with headless and multi-channel selling", endpoint: "https://api.bigcommerce.com/stores/{store_hash}/v3", protocol: "REST", capabilities: "products, orders, customers, carts, channels, payments", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://developer.bigcommerce.com/docs/rest-management", authUrl: "https://www.bigcommerce.com/start-your-trial/", contactUrl: "https://support.bigcommerce.com/s/contact" },
  { serviceName: "stripe-connect", description: "Platform payments and marketplace infrastructure", endpoint: "https://api.stripe.com/v1", protocol: "REST", capabilities: "connected accounts, transfers, payouts, onboarding, identity", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.stripe.com/connect", authUrl: "https://dashboard.stripe.com/register", contactUrl: "https://support.stripe.com/contact" },
  { serviceName: "amazon-sp-api", description: "Amazon Selling Partner API for marketplace operations", endpoint: "https://sellingpartnerapi-na.amazon.com", protocol: "REST", capabilities: "orders, inventory, pricing, reports, feeds, catalog items", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developer-docs.amazon.com/sp-api/", authUrl: "https://sellercentral.amazon.com/apps/store/dp/amzn1.sellerapps.app", contactUrl: "https://sellercentral.amazon.com/help" },
  { serviceName: "ebay-browse-api", description: "eBay marketplace API for searching and viewing listings", endpoint: "https://api.ebay.com/buy/browse/v1", protocol: "REST", capabilities: "item search, item details, product images, compatibility", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developer.ebay.com/api-docs/buy/browse/overview.html", authUrl: "https://developer.ebay.com/signin", contactUrl: "https://developer.ebay.com/support" },
  { serviceName: "etsy-open-api", description: "Etsy marketplace API for handmade and vintage goods", endpoint: "https://openapi.etsy.com/v3", protocol: "REST", capabilities: "listings, shops, receipts, users, images, shipping", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developers.etsy.com/documentation/", authUrl: "https://www.etsy.com/developers/register", contactUrl: "https://www.etsy.com/developers/support" },
  { serviceName: "snipcart", description: "Shopping cart platform for any website with HTML attributes", endpoint: "https://app.snipcart.com/api", protocol: "REST", capabilities: "cart, products, orders, discounts, subscriptions, abandoned carts", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.snipcart.com/v3/api-reference/introduction", authUrl: "https://app.snipcart.com/register", contactUrl: "https://snipcart.com/contact-us" },
  { serviceName: "commercetools", description: "Headless commerce platform with composable architecture", endpoint: "https://api.{region}.commercetools.com/{project-key}", protocol: "REST", capabilities: "products, carts, orders, customers, inventory, subscriptions", pricingModel: "contact", authMethod: "OAuth2", docsUrl: "https://docs.commercetools.com/api/", authUrl: "https://commercetools.com/free-trial", contactUrl: "https://commercetools.com/contact" },

  // ─── 4. Social Media ───────────────────────────────────────────────
  { serviceName: "twitter-x-api", description: "X (formerly Twitter) API for tweets, users, and spaces", endpoint: "https://api.twitter.com/2", protocol: "REST", capabilities: "tweets, users, spaces, lists, bookmarks, direct messages", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://developer.twitter.com/en/docs", authUrl: "https://developer.twitter.com/en/portal/dashboard", contactUrl: "https://help.twitter.com/en/forms" },
  { serviceName: "meta-graph-api", description: "Meta Graph API for Facebook, Instagram, and Threads", endpoint: "https://graph.facebook.com/v18.0", protocol: "REST", capabilities: "pages, posts, media, insights, ads, Reels, Stories", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developers.facebook.com/docs/graph-api/", authUrl: "https://developers.facebook.com/apps/", contactUrl: "https://developers.facebook.com/support/" },
  { serviceName: "linkedin-api", description: "LinkedIn API for profiles, posts, and company pages", endpoint: "https://api.linkedin.com/v2", protocol: "REST", capabilities: "profile, posts, company pages, ads, UGC, analytics", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://learn.microsoft.com/en-us/linkedin/", authUrl: "https://www.linkedin.com/developers/apps", contactUrl: "https://www.linkedin.com/help/linkedin" },
  { serviceName: "reddit-api", description: "Reddit API for subreddits, posts, comments, and moderation", endpoint: "https://oauth.reddit.com/api/v1", protocol: "REST", capabilities: "posts, comments, subreddits, voting, moderation, flair", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://www.reddit.com/dev/api/", authUrl: "https://www.reddit.com/prefs/apps", contactUrl: "https://support.reddithelp.com/hc/en-us" },
  { serviceName: "pinterest-api", description: "Pinterest API for pins, boards, and ad management", endpoint: "https://api.pinterest.com/v5", protocol: "REST", capabilities: "pins, boards, ads, analytics, catalogs, audiences", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developers.pinterest.com/docs/api/v5/", authUrl: "https://developers.pinterest.com/apps/", contactUrl: "https://help.pinterest.com/en/contact" },
  { serviceName: "tiktok-api", description: "TikTok API for content publishing and creator tools", endpoint: "https://open.tiktokapis.com/v2", protocol: "REST", capabilities: "video publishing, user info, video list, content posting", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developers.tiktok.com/doc/", authUrl: "https://developers.tiktok.com/apps/", contactUrl: "https://developers.tiktok.com/support" },
  { serviceName: "youtube-data-api", description: "YouTube API for video, channel, and playlist management", endpoint: "https://www.googleapis.com/youtube/v3", protocol: "REST", capabilities: "videos, channels, playlists, search, live streaming, comments", pricingModel: "free", authMethod: "API key", docsUrl: "https://developers.google.com/youtube/v3/docs", authUrl: "https://console.cloud.google.com/apis/credentials", contactUrl: "https://support.google.com/youtube/answer/3545535" },
  { serviceName: "mastodon-api", description: "Decentralized social network API compatible with ActivityPub", endpoint: "https://{instance}/api/v1", protocol: "REST", capabilities: "statuses, timelines, notifications, search, media, polls", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://docs.joinmastodon.org/api/", authUrl: "https://mastodon.social/auth/sign_up", contactUrl: "https://joinmastodon.org/about" },
  { serviceName: "bluesky-api", description: "Bluesky social network built on the AT Protocol", endpoint: "https://bsky.social/xrpc", protocol: "REST", capabilities: "posts, feeds, profiles, notifications, labeling, moderation", pricingModel: "free", authMethod: "Bearer token", docsUrl: "https://docs.bsky.app/", authUrl: "https://bsky.app/", contactUrl: "https://blueskyweb.zendesk.com/hc/en-us" },

  // ─── 5. Storage & CDN ──────────────────────────────────────────────
  { serviceName: "backblaze-b2", description: "Affordable S3-compatible cloud object storage", endpoint: "https://api.backblazeb2.com/b2api/v3", protocol: "REST", capabilities: "object storage, lifecycle rules, S3 compatibility, replication", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.backblaze.com/apidocs/", authUrl: "https://www.backblaze.com/sign-up/cloud-storage", contactUrl: "https://www.backblaze.com/company/contact.html" },
  { serviceName: "wasabi", description: "Hot cloud storage with no egress fees and S3 compatibility", endpoint: "https://s3.wasabisys.com", protocol: "REST", capabilities: "object storage, versioning, S3 compatible, immutable buckets", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://docs.wasabi.com/", authUrl: "https://console.wasabisys.com/#/login", contactUrl: "https://wasabi.com/contact/" },
  { serviceName: "digitalocean-spaces", description: "S3-compatible object storage with built-in CDN", endpoint: "https://{region}.digitaloceanspaces.com", protocol: "REST", capabilities: "object storage, CDN, S3 compatible, CORS, lifecycle", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://docs.digitalocean.com/products/spaces/", authUrl: "https://cloud.digitalocean.com/registrations/new", contactUrl: "https://www.digitalocean.com/company/contact" },
  { serviceName: "bunny-cdn", description: "Global content delivery network with edge storage", endpoint: "https://api.bunny.net", protocol: "REST", capabilities: "CDN, edge storage, image processing, DNS, stream", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.bunny.net/reference/bunnynet-api-overview", authUrl: "https://dash.bunny.net/auth/register", contactUrl: "https://bunny.net/contact" },
  { serviceName: "fastly", description: "Edge cloud platform with CDN, compute, and security", endpoint: "https://api.fastly.com", protocol: "REST", capabilities: "CDN, edge compute, WAF, image optimization, streaming", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.fastly.com/documentation/reference/api/", authUrl: "https://www.fastly.com/signup/", contactUrl: "https://www.fastly.com/contact" },
  { serviceName: "keycdn", description: "High-performance content delivery network", endpoint: "https://api.keycdn.com", protocol: "REST", capabilities: "CDN, image processing, SSL, real-time analytics, zones", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.keycdn.com/api", authUrl: "https://app.keycdn.com/signup", contactUrl: "https://www.keycdn.com/contact" },
  { serviceName: "linode-object-storage", description: "S3-compatible object storage from Akamai/Linode", endpoint: "https://{cluster}.linodeobjects.com", protocol: "REST", capabilities: "object storage, S3 compatible, static site hosting, lifecycle", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://www.linode.com/docs/products/storage/object-storage/", authUrl: "https://login.linode.com/signup", contactUrl: "https://www.linode.com/support/" },
  { serviceName: "cloudflare-r2", description: "S3-compatible object storage with zero egress fees", endpoint: "https://{account_id}.r2.cloudflarestorage.com", protocol: "REST", capabilities: "object storage, S3 compatible, zero egress, Workers integration", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://developers.cloudflare.com/r2/", authUrl: "https://dash.cloudflare.com/sign-up", contactUrl: "https://www.cloudflare.com/plans/enterprise/contact/" },

  // ─── 6. DevOps & CI/CD ─────────────────────────────────────────────
  { serviceName: "circleci", description: "Continuous integration and delivery platform", endpoint: "https://circleci.com/api/v2", protocol: "REST", capabilities: "CI/CD pipelines, orbs, workflows, insights, runners", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://circleci.com/docs/api/v2/", authUrl: "https://circleci.com/signup/", contactUrl: "https://support.circleci.com/hc/en-us" },
  { serviceName: "travis-ci", description: "Continuous integration service for open source and private projects", endpoint: "https://api.travis-ci.com", protocol: "REST", capabilities: "CI builds, deployments, cron jobs, build matrix", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://developer.travis-ci.com/", authUrl: "https://app.travis-ci.com/signup", contactUrl: "https://www.travis-ci.com/contact-us/" },
  { serviceName: "buildkite", description: "CI/CD platform with hybrid cloud runners", endpoint: "https://api.buildkite.com/v2", protocol: "REST", capabilities: "pipelines, builds, artifacts, agents, test analytics", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://buildkite.com/docs/apis/rest-api", authUrl: "https://buildkite.com/signup", contactUrl: "https://buildkite.com/contact" },
  { serviceName: "drone-ci", description: "Container-native continuous integration platform", endpoint: "https://cloud.drone.io/api", protocol: "REST", capabilities: "pipelines, secrets, cron, plugins, multi-platform builds", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://docs.drone.io/api/overview/", authUrl: "https://cloud.drone.io/login", contactUrl: "https://discourse.drone.io/" },
  { serviceName: "terraform-cloud", description: "Infrastructure as code collaboration and automation platform", endpoint: "https://app.terraform.io/api/v2", protocol: "REST", capabilities: "workspaces, runs, state management, policy, registry", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://developer.hashicorp.com/terraform/cloud-docs/api-docs", authUrl: "https://app.terraform.io/signup/account", contactUrl: "https://www.hashicorp.com/contact-sales" },
  { serviceName: "pulumi", description: "Infrastructure as code using general-purpose programming languages", endpoint: "https://api.pulumi.com/api", protocol: "REST", capabilities: "stacks, deployments, previews, secrets, policy, ESC", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://www.pulumi.com/docs/pulumi-cloud/cloud-rest-api/", authUrl: "https://app.pulumi.com/signup", contactUrl: "https://www.pulumi.com/contact/" },
  { serviceName: "ansible-automation-platform", description: "Enterprise automation platform for IT operations", endpoint: "https://{tower}/api/v2", protocol: "REST", capabilities: "playbooks, inventories, job templates, credentials, workflows", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://docs.ansible.com/automation-controller/latest/html/controllerapi/", authUrl: "https://www.redhat.com/en/technologies/management/ansible/trial", contactUrl: "https://www.redhat.com/en/about/contact" },
  { serviceName: "argocd", description: "Declarative GitOps continuous delivery for Kubernetes", endpoint: "https://{argocd-server}/api/v1", protocol: "REST", capabilities: "application sync, rollouts, RBAC, SSO, multi-cluster", pricingModel: "free", authMethod: "Bearer token", docsUrl: "https://argo-cd.readthedocs.io/en/stable/developer-guide/api-docs/", authUrl: "https://github.com/argoproj/argo-cd", contactUrl: "https://argoproj.github.io/community/" },
  { serviceName: "spacelift", description: "Infrastructure as code management platform for Terraform and more", endpoint: "https://{account}.app.spacelift.io/graphql", protocol: "GraphQL", capabilities: "stacks, runs, policies, drift detection, modules, blueprints", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://docs.spacelift.io/", authUrl: "https://spacelift.io/free-trial", contactUrl: "https://spacelift.io/contact" },

  // ─── 7. Databases & Caching ────────────────────────────────────────
  { serviceName: "cockroachdb", description: "Distributed SQL database built for cloud-native applications", endpoint: "https://cockroachlabs.cloud/api/v1", protocol: "REST", capabilities: "distributed SQL, multi-region, serverless, backup, CDC", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.cockroachlabs.com/docs/api/cloud/v1", authUrl: "https://cockroachlabs.cloud/signup", contactUrl: "https://www.cockroachlabs.com/contact/" },
  { serviceName: "momento-cache", description: "Serverless caching service with instant provisioning", endpoint: "https://api.cache.cell-1-us-west-2-1.prod.a.]momentohq.com", protocol: "gRPC", capabilities: "caching, topics (pub/sub), sorted sets, dictionaries, TTL", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.momentohq.com/", authUrl: "https://console.gomomento.com/signup", contactUrl: "https://www.gomomento.com/contact-us" },
  { serviceName: "faunadb", description: "Distributed document-relational database with native GraphQL", endpoint: "https://db.fauna.com", protocol: "REST", capabilities: "document-relational, FQL, GraphQL, ABAC, temporality, streaming", pricingModel: "per-request", authMethod: "Bearer token", docsUrl: "https://docs.fauna.com/", authUrl: "https://dashboard.fauna.com/register", contactUrl: "https://fauna.com/contact-us" },
  { serviceName: "dynamodb", description: "AWS fully managed NoSQL key-value and document database", endpoint: "https://dynamodb.{region}.amazonaws.com", protocol: "REST", capabilities: "key-value, document, global tables, streams, DAX caching, TTL", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/", authUrl: "https://aws.amazon.com/free/", contactUrl: "https://aws.amazon.com/contact-us/" },
  { serviceName: "surrealdb", description: "Multi-model database for web, mobile, serverless, and backend", endpoint: "https://cloud.surrealdb.com", protocol: "REST", capabilities: "SQL-like queries, graph, document, key-value, real-time, auth", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://surrealdb.com/docs/", authUrl: "https://surrealdb.com/signup", contactUrl: "https://surrealdb.com/contact" },
  { serviceName: "xata", description: "Serverless database platform with search and analytics built in", endpoint: "https://{workspace}.{region}.xata.sh/db/{database}", protocol: "REST", capabilities: "database, full-text search, vector search, file attachments, branches", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://xata.io/docs/", authUrl: "https://app.xata.io/signin", contactUrl: "https://xata.io/contact" },
  { serviceName: "tigris-data", description: "Globally distributed S3-compatible object storage with search", endpoint: "https://fly.storage.tigris.dev", protocol: "REST", capabilities: "object storage, global caching, S3 compatible, metadata search", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.tigrisdata.com/docs/", authUrl: "https://console.tigris.dev/signup", contactUrl: "https://www.tigrisdata.com/contact/" },

  // ─── 8. Document & PDF ─────────────────────────────────────────────
  { serviceName: "hellosign", description: "Electronic signature API from Dropbox for document signing", endpoint: "https://api.hellosign.com/v3", protocol: "REST", capabilities: "signature requests, templates, embedded signing, team management", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.hellosign.com/", authUrl: "https://app.hellosign.com/account/signUp", contactUrl: "https://faq.hellosign.com/hc/en-us" },
  { serviceName: "adobe-pdf-services", description: "Adobe cloud-based PDF manipulation and document generation", endpoint: "https://pdf-services.adobe.io", protocol: "REST", capabilities: "PDF creation, conversion, OCR, compression, extraction, merge", pricingModel: "per-request", authMethod: "OAuth2", docsUrl: "https://developer.adobe.com/document-services/docs/overview/", authUrl: "https://acrobatservices.adobe.com/dc-integration-creation-app-cdn/main.html", contactUrl: "https://developer.adobe.com/document-services/pricing/contact/sales/" },
  { serviceName: "pdfmonkey", description: "PDF generation API from HTML templates with dynamic data", endpoint: "https://api.pdfmonkey.io/api/v1", protocol: "REST", capabilities: "PDF generation, HTML templates, dynamic data, batch, webhooks", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://docs.pdfmonkey.io/", authUrl: "https://dashboard.pdfmonkey.io/signup", contactUrl: "https://www.pdfmonkey.io/contact" },
  { serviceName: "gotenberg", description: "Docker-based API for converting HTML, Markdown, and Office docs to PDF", endpoint: "https://{instance}:3000/forms", protocol: "REST", capabilities: "HTML to PDF, Markdown to PDF, Office conversion, merge, screenshots", pricingModel: "free", authMethod: "none", docsUrl: "https://gotenberg.dev/docs/about", authUrl: "https://github.com/gotenberg/gotenberg", contactUrl: "https://github.com/gotenberg/gotenberg/discussions" },
  { serviceName: "convertapi", description: "File conversion API supporting 200+ formats", endpoint: "https://v2.convertapi.com", protocol: "REST", capabilities: "PDF conversion, document merging, image conversion, OCR, watermarks", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.convertapi.com/doc", authUrl: "https://www.convertapi.com/a/signup", contactUrl: "https://www.convertapi.com/support" },
  { serviceName: "anvil-api", description: "Paperwork automation for PDF generation and e-signatures", endpoint: "https://app.useanvil.com/api/v1", protocol: "REST", capabilities: "PDF filling, generation, e-signatures, workflows, Etch signing", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.useanvil.com/docs/api/", authUrl: "https://app.useanvil.com/signup", contactUrl: "https://www.useanvil.com/contact/" },

  // ─── 9. Translation & i18n ─────────────────────────────────────────
  { serviceName: "deepl", description: "AI-powered language translation with exceptional quality", endpoint: "https://api-free.deepl.com/v2", protocol: "REST", capabilities: "text translation, document translation, glossaries, formality", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.deepl.com/docs", authUrl: "https://www.deepl.com/pro-api", contactUrl: "https://www.deepl.com/contact-us" },
  { serviceName: "lokalise", description: "Translation management platform for agile teams", endpoint: "https://api.lokalise.com/api2", protocol: "REST", capabilities: "translation management, keys, files, tasks, team collaboration", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://developers.lokalise.com/reference/", authUrl: "https://app.lokalise.com/signup", contactUrl: "https://lokalise.com/contact" },
  { serviceName: "crowdin", description: "Localization management platform for software and content", endpoint: "https://api.crowdin.com/api/v2", protocol: "REST", capabilities: "localization, translation memory, glossaries, MT engines, QA", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://support.crowdin.com/developer/api/v2/", authUrl: "https://accounts.crowdin.com/register", contactUrl: "https://crowdin.com/contacts" },
  { serviceName: "transifex", description: "Localization and translation platform with automation", endpoint: "https://rest.api.transifex.com", protocol: "REST", capabilities: "resource strings, translations, projects, teams, webhooks", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://developers.transifex.com/reference/api-introduction", authUrl: "https://app.transifex.com/signup/", contactUrl: "https://www.transifex.com/contact/" },
  { serviceName: "phrase", description: "Translation management system for software localization", endpoint: "https://api.phrase.com/v2", protocol: "REST", capabilities: "keys, locales, translations, uploads, glossaries, webhooks", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://developers.phrase.com/api/", authUrl: "https://app.phrase.com/signup", contactUrl: "https://phrase.com/contact/" },

  // ─── 10. Scheduling & Calendar ─────────────────────────────────────
  { serviceName: "calendly", description: "Scheduling automation platform for meetings and appointments", endpoint: "https://api.calendly.com", protocol: "REST", capabilities: "event types, scheduled events, invitees, availability, webhooks", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://developer.calendly.com/api-docs", authUrl: "https://calendly.com/signup", contactUrl: "https://calendly.com/contact" },
  { serviceName: "nylas", description: "Email, calendar, and contacts APIs for application integration", endpoint: "https://api.us.nylas.com/v3", protocol: "REST", capabilities: "email, calendar, contacts, scheduling, webhooks, virtual calendars", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://developer.nylas.com/docs/api/", authUrl: "https://dashboard.nylas.com/register", contactUrl: "https://www.nylas.com/company/contact-us/" },
  { serviceName: "cronofy", description: "Calendar API for scheduling and availability management", endpoint: "https://api.cronofy.com/v1", protocol: "REST", capabilities: "calendar sync, availability, scheduling, real-time scheduling links", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://docs.cronofy.com/", authUrl: "https://app.cronofy.com/sign_up/developer", contactUrl: "https://www.cronofy.com/contact" },
  { serviceName: "savvycal", description: "Scheduling tool with recipient-first booking experience", endpoint: "https://api.savvycal.com/v1", protocol: "REST", capabilities: "scheduling links, availability, polls, round robin, workflows", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://savvycal.com/docs/api/", authUrl: "https://savvycal.com/signup", contactUrl: "https://savvycal.com/contact" },

  // ─── 11. HR & Recruiting ───────────────────────────────────────────
  { serviceName: "greenhouse", description: "Applicant tracking and recruiting software for growing companies", endpoint: "https://harvest.greenhouse.io/v1", protocol: "REST", capabilities: "candidates, applications, jobs, scorecards, offers, EEOC", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://developers.greenhouse.io/harvest.html", authUrl: "https://www.greenhouse.com/", contactUrl: "https://www.greenhouse.com/contact" },
  { serviceName: "lever", description: "Talent acquisition suite for recruiting and hiring", endpoint: "https://api.lever.co/v1", protocol: "REST", capabilities: "opportunities, candidates, postings, interviews, offers, referrals", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://hire.lever.co/developer/documentation", authUrl: "https://www.lever.co/contact-us/", contactUrl: "https://www.lever.co/contact-us/" },
  { serviceName: "bamboohr", description: "HR software platform for small and medium businesses", endpoint: "https://api.bamboohr.com/api/gateway.php/{companyDomain}/v1", protocol: "REST", capabilities: "employees, time off, benefits, reports, custom fields, webhooks", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://documentation.bamboohr.com/reference", authUrl: "https://www.bamboohr.com/signup/", contactUrl: "https://www.bamboohr.com/contact/" },
  { serviceName: "gusto-api", description: "Payroll, benefits, and HR management platform API", endpoint: "https://api.gusto.com/v1", protocol: "REST", capabilities: "payroll, employees, benefits, time tracking, contractors", pricingModel: "subscription", authMethod: "OAuth2", docsUrl: "https://docs.gusto.com/", authUrl: "https://dev.gusto.com/", contactUrl: "https://gusto.com/contact" },
  { serviceName: "rippling", description: "Workforce platform for HR, IT, and finance operations", endpoint: "https://api.rippling.com", protocol: "REST", capabilities: "employees, payroll, benefits, devices, app management, SCIM", pricingModel: "subscription", authMethod: "OAuth2", docsUrl: "https://developer.rippling.com/docs/rippling-api/", authUrl: "https://www.rippling.com/request-demo", contactUrl: "https://www.rippling.com/contact-sales" },

  // ─── 12. Legal & Compliance ────────────────────────────────────────
  { serviceName: "ironclad", description: "Digital contract lifecycle management platform", endpoint: "https://ironcladapp.com/public/api/v1", protocol: "REST", capabilities: "contracts, workflows, approvals, templates, clause library", pricingModel: "contact", authMethod: "Bearer token", docsUrl: "https://developer.ironcladapp.com/docs", authUrl: "https://ironcladapp.com/request-demo/", contactUrl: "https://ironcladapp.com/contact/" },
  { serviceName: "vanta", description: "Compliance automation for SOC 2, ISO 27001, and HIPAA", endpoint: "https://api.vanta.com/v1", protocol: "REST", capabilities: "evidence collection, risk management, vendor reviews, compliance monitoring", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://developer.vanta.com/", authUrl: "https://www.vanta.com/request-demo", contactUrl: "https://www.vanta.com/contact" },
  { serviceName: "drata", description: "Compliance automation platform for security frameworks", endpoint: "https://public-api.drata.com", protocol: "REST", capabilities: "controls monitoring, evidence collection, risk assessment, vendor management", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://developers.drata.com/docs/", authUrl: "https://drata.com/demo", contactUrl: "https://drata.com/contact" },

  // ─── 13. Healthcare ────────────────────────────────────────────────
  { serviceName: "epic-fhir", description: "Epic EHR FHIR API for patient data interoperability", endpoint: "https://fhir.epic.com/interconnect-fhir-oauth", protocol: "REST", capabilities: "patient records, observations, medications, allergies, FHIR R4", pricingModel: "contact", authMethod: "OAuth2", docsUrl: "https://fhir.epic.com/Documentation", authUrl: "https://fhir.epic.com/Developer/Apps", contactUrl: "https://www.epic.com/contact" },
  { serviceName: "oracle-health-cerner", description: "Oracle Health (Cerner) FHIR API for clinical data exchange", endpoint: "https://fhir-open.cerner.com/r4", protocol: "REST", capabilities: "patient records, encounters, diagnostics, medications, FHIR R4", pricingModel: "contact", authMethod: "OAuth2", docsUrl: "https://fhir.cerner.com/", authUrl: "https://code.cerner.com/developer/smart-on-fhir/", contactUrl: "https://www.oracle.com/health/contact/" },
  { serviceName: "athenahealth", description: "Cloud-based EHR and practice management FHIR APIs", endpoint: "https://api.platform.athenahealth.com/fhir/r4", protocol: "REST", capabilities: "patients, appointments, clinical data, claims, FHIR R4", pricingModel: "contact", authMethod: "OAuth2", docsUrl: "https://docs.athenahealth.com/api/", authUrl: "https://developer.athenahealth.com/", contactUrl: "https://www.athenahealth.com/contact-us" },
  { serviceName: "healthgorilla", description: "Health data interoperability platform for lab results and records", endpoint: "https://api.healthgorilla.com/fhir/R4", protocol: "REST", capabilities: "lab orders, clinical documents, patient matching, FHIR", pricingModel: "contact", authMethod: "OAuth2", docsUrl: "https://developer.healthgorilla.com/docs", authUrl: "https://www.healthgorilla.com/contact", contactUrl: "https://www.healthgorilla.com/contact" },

  // ─── 14. Finance & Crypto ──────────────────────────────────────────
  { serviceName: "alpaca-trading", description: "Commission-free stock and crypto trading API", endpoint: "https://api.alpaca.markets/v2", protocol: "REST", capabilities: "stock trading, crypto trading, market data, account management, paper trading", pricingModel: "free", authMethod: "API key", docsUrl: "https://docs.alpaca.markets/", authUrl: "https://app.alpaca.markets/signup", contactUrl: "https://alpaca.markets/support" },
  { serviceName: "binance-api", description: "Cryptocurrency exchange API for trading and market data", endpoint: "https://api.binance.com/api/v3", protocol: "REST", capabilities: "spot trading, futures, market data, wallet, staking, savings", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://developers.binance.com/docs/binance-spot-api-docs/rest-api", authUrl: "https://www.binance.com/en/register", contactUrl: "https://www.binance.com/en/support" },
  { serviceName: "moralis", description: "Web3 data API for blockchain development", endpoint: "https://deep-index.moralis.io/api/v2.2", protocol: "REST", capabilities: "wallet data, NFT data, token data, DeFi, streams, price feeds", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.moralis.io/", authUrl: "https://admin.moralis.io/register", contactUrl: "https://moralis.io/contact/" },
  { serviceName: "alchemy", description: "Web3 development platform with blockchain APIs and infrastructure", endpoint: "https://eth-mainnet.g.alchemy.com/v2", protocol: "REST", capabilities: "node API, NFT API, transfers, webhooks, gas optimization, token API", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.alchemy.com/", authUrl: "https://auth.alchemy.com/signup", contactUrl: "https://www.alchemy.com/contact-us" },
  { serviceName: "infura", description: "Ethereum and IPFS infrastructure for decentralized applications", endpoint: "https://mainnet.infura.io/v3", protocol: "REST", capabilities: "Ethereum JSON-RPC, IPFS, layer 2 networks, archive data", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.infura.io/", authUrl: "https://app.infura.io/register", contactUrl: "https://www.infura.io/contact" },
  { serviceName: "quicknode", description: "Blockchain infrastructure with multi-chain node access", endpoint: "https://{endpoint}.quiknode.pro", protocol: "REST", capabilities: "node access, NFT API, token API, streams, functions, marketplace", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.quicknode.com/docs", authUrl: "https://www.quicknode.com/signup", contactUrl: "https://www.quicknode.com/contact-us" },
  { serviceName: "polygon-io", description: "Financial market data API for stocks, options, forex, and crypto", endpoint: "https://api.polygon.io/v2", protocol: "REST", capabilities: "stock quotes, options, forex, crypto, news, fundamentals", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://polygon.io/docs/", authUrl: "https://polygon.io/dashboard/signup", contactUrl: "https://polygon.io/contact" },
  { serviceName: "plaid", description: "Financial data connectivity platform for banking and fintech", endpoint: "https://production.plaid.com", protocol: "REST", capabilities: "account linking, transactions, identity, balance, investments, liabilities", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://plaid.com/docs/", authUrl: "https://dashboard.plaid.com/signup", contactUrl: "https://plaid.com/contact/" },

  // ─── 15. AI Agents & Tools ─────────────────────────────────────────
  { serviceName: "mlflow", description: "Open source platform for ML lifecycle management", endpoint: "https://{tracking-server}/api/2.0/mlflow", protocol: "REST", capabilities: "experiment tracking, model registry, model serving, projects", pricingModel: "free", authMethod: "Bearer token", docsUrl: "https://mlflow.org/docs/latest/rest-api.html", authUrl: "https://github.com/mlflow/mlflow", contactUrl: "https://github.com/mlflow/mlflow/issues" },
  { serviceName: "neptune-ai", description: "Experiment tracking and model registry for ML teams", endpoint: "https://api.neptune.ai/api/v1", protocol: "REST", capabilities: "experiment tracking, model registry, data versioning, dashboards", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.neptune.ai/api/", authUrl: "https://app.neptune.ai/register/", contactUrl: "https://neptune.ai/contact" },
  { serviceName: "comet-ml", description: "ML experiment management and model production monitoring", endpoint: "https://www.comet.com/api/rest/v2", protocol: "REST", capabilities: "experiment tracking, model monitoring, panels, artifacts", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.comet.com/docs/v2/api-and-sdk/rest-api/overview/", authUrl: "https://www.comet.com/signup", contactUrl: "https://www.comet.com/contact-us" },
  { serviceName: "roboflow", description: "Computer vision platform for building and deploying models", endpoint: "https://api.roboflow.com", protocol: "REST", capabilities: "dataset management, model training, inference, annotation, deployment", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.roboflow.com/", authUrl: "https://app.roboflow.com/login", contactUrl: "https://roboflow.com/contact" },
  { serviceName: "scale-ai", description: "Data labeling and AI platform for enterprise machine learning", endpoint: "https://api.scale.com/v1", protocol: "REST", capabilities: "data labeling, model evaluation, RLHF, synthetic data", pricingModel: "contact", authMethod: "API key", docsUrl: "https://docs.scale.com/reference", authUrl: "https://dashboard.scale.com/signup", contactUrl: "https://scale.com/contact" },
  { serviceName: "openrouter", description: "Unified API gateway for accessing multiple LLM providers", endpoint: "https://openrouter.ai/api/v1", protocol: "REST", capabilities: "multi-model routing, chat completions, model comparison, fallbacks", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://openrouter.ai/docs", authUrl: "https://openrouter.ai/keys", contactUrl: "https://openrouter.ai/contact" },
  { serviceName: "anyscale", description: "Scalable AI compute platform built on Ray for training and serving", endpoint: "https://api.endpoints.anyscale.com/v1", protocol: "REST", capabilities: "model serving, fine-tuning, batch inference, Ray clusters", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.anyscale.com/", authUrl: "https://console.anyscale.com/register", contactUrl: "https://www.anyscale.com/contact-us" },

  // ─── 16. Image/Design ──────────────────────────────────────────────
  { serviceName: "canva-api", description: "Design platform API for creating and editing visual content", endpoint: "https://api.canva.com/rest/v1", protocol: "REST", capabilities: "design creation, templates, brand kit, content publishing, autofill", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://www.canva.dev/docs/connect/", authUrl: "https://www.canva.com/developers/", contactUrl: "https://www.canva.com/help/contact/" },
  { serviceName: "remove-bg", description: "AI-powered background removal from images", endpoint: "https://api.remove.bg/v1.0", protocol: "REST", capabilities: "background removal, HD output, car background, batch processing", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.remove.bg/api", authUrl: "https://www.remove.bg/users/sign_up", contactUrl: "https://www.remove.bg/support" },
  { serviceName: "unsplash-api", description: "Free high-resolution photography API with millions of images", endpoint: "https://api.unsplash.com", protocol: "REST", capabilities: "photo search, random photos, collections, user profiles, statistics", pricingModel: "free", authMethod: "API key", docsUrl: "https://unsplash.com/documentation", authUrl: "https://unsplash.com/developers", contactUrl: "https://help.unsplash.com/en/" },
  { serviceName: "pexels-api", description: "Free stock photos and videos API for creative projects", endpoint: "https://api.pexels.com/v1", protocol: "REST", capabilities: "photo search, curated photos, video search, collections", pricingModel: "free", authMethod: "API key", docsUrl: "https://www.pexels.com/api/documentation/", authUrl: "https://www.pexels.com/api/new/", contactUrl: "https://www.pexels.com/contact/" },
  { serviceName: "giphy-api", description: "GIF search and discovery API with trending and category content", endpoint: "https://api.giphy.com/v1", protocol: "REST", capabilities: "GIF search, trending, translate, random, stickers, upload", pricingModel: "free", authMethod: "API key", docsUrl: "https://developers.giphy.com/docs/api/", authUrl: "https://developers.giphy.com/dashboard/", contactUrl: "https://support.giphy.com/hc/en-us" },
  { serviceName: "placeholder-api", description: "Dynamic placeholder image generation service", endpoint: "https://api.placeholder.com", protocol: "REST", capabilities: "placeholder images, custom sizes, colors, text overlays", pricingModel: "free", authMethod: "none", docsUrl: "https://placeholder.com/", contactUrl: "https://placeholder.com/" },
  { serviceName: "imagekit", description: "Real-time image and video optimization and transformation CDN", endpoint: "https://api.imagekit.io/v1", protocol: "REST", capabilities: "image optimization, transformation, CDN delivery, DAM, video", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.imagekit.io/api-reference/", authUrl: "https://imagekit.io/registration/", contactUrl: "https://imagekit.io/contact-us/" },

  // ─── 17. Video ─────────────────────────────────────────────────────
  { serviceName: "vimeo-api", description: "Video hosting and streaming platform API", endpoint: "https://api.vimeo.com", protocol: "REST", capabilities: "video upload, management, player, analytics, live streaming, OTT", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://developer.vimeo.com/api/reference", authUrl: "https://developer.vimeo.com/apps/new", contactUrl: "https://vimeo.com/help/contact" },
  { serviceName: "wistia", description: "Video hosting platform for business with marketing tools", endpoint: "https://api.wistia.com/v1", protocol: "REST", capabilities: "video hosting, player customization, analytics, channels, captions", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://wistia.com/support/developers", authUrl: "https://app.wistia.com/signup", contactUrl: "https://wistia.com/support/contact" },
  { serviceName: "brightcove", description: "Enterprise video hosting and streaming platform", endpoint: "https://cms.api.brightcove.com/v1", protocol: "REST", capabilities: "video management, live streaming, analytics, DRM, SSAI", pricingModel: "subscription", authMethod: "OAuth2", docsUrl: "https://apis.support.brightcove.com/", authUrl: "https://studio.brightcove.com/products/registrationpage", contactUrl: "https://www.brightcove.com/en/company/contact-us/" },
  { serviceName: "api-video", description: "Video infrastructure API for upload, encoding, and delivery", endpoint: "https://ws.api.video", protocol: "REST", capabilities: "video upload, live streaming, player, analytics, watermarking", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.api.video/reference", authUrl: "https://dashboard.api.video/register", contactUrl: "https://api.video/contact-us" },
  { serviceName: "cloudflare-stream", description: "Serverless video streaming and storage at the edge", endpoint: "https://api.cloudflare.com/client/v4/accounts/{account_id}/stream", protocol: "REST", capabilities: "video upload, live streaming, player, storage, captions, clipping", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://developers.cloudflare.com/stream/", authUrl: "https://dash.cloudflare.com/sign-up", contactUrl: "https://www.cloudflare.com/plans/enterprise/contact/" },

  // ─── 18. Audio & Music ─────────────────────────────────────────────
  { serviceName: "spotify-web-api", description: "Spotify API for music data, playback, and playlist management", endpoint: "https://api.spotify.com/v1", protocol: "REST", capabilities: "search, playlists, playback, recommendations, artists, albums, user library", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developer.spotify.com/documentation/web-api", authUrl: "https://developer.spotify.com/dashboard", contactUrl: "https://developer.spotify.com/community" },
  { serviceName: "soundcloud-api", description: "Audio distribution platform API for tracks and playlists", endpoint: "https://api.soundcloud.com", protocol: "REST", capabilities: "tracks, playlists, users, comments, stream, upload", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://developers.soundcloud.com/docs/api/guide", authUrl: "https://soundcloud.com/you/apps", contactUrl: "https://help.soundcloud.com/hc/en-us" },
  { serviceName: "descript", description: "AI-powered audio and video editing platform", endpoint: "https://api.descript.com/v2", protocol: "REST", capabilities: "transcription, audio editing, video editing, screen recording, overdub", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://developers.descript.com/", authUrl: "https://web.descript.com/signup", contactUrl: "https://www.descript.com/contact" },
  { serviceName: "otter-ai", description: "AI meeting transcription and note-taking assistant", endpoint: "https://otter.ai/forward/api/v1", protocol: "REST", capabilities: "meeting transcription, summaries, action items, speaker identification", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://otter.ai/integrations", authUrl: "https://otter.ai/signup", contactUrl: "https://help.otter.ai/hc/en-us" },
  { serviceName: "audiomack", description: "Music streaming and discovery platform API", endpoint: "https://api.audiomack.com/v1", protocol: "REST", capabilities: "music upload, streaming, playlists, trending, charts", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://www.audiomack.com/data-api/docs", authUrl: "https://www.audiomack.com/signup", contactUrl: "https://www.audiomack.com/contact" },

  // ─── 19. Project Management ────────────────────────────────────────
  { serviceName: "jira-api", description: "Atlassian Jira project tracking and issue management API", endpoint: "https://your-domain.atlassian.net/rest/api/3", protocol: "REST", capabilities: "issues, projects, boards, sprints, workflows, JQL search", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/", authUrl: "https://id.atlassian.com/signup", contactUrl: "https://support.atlassian.com/contact/" },
  { serviceName: "asana-api", description: "Work management platform API for teams and projects", endpoint: "https://app.asana.com/api/1.0", protocol: "REST", capabilities: "tasks, projects, portfolios, goals, custom fields, webhooks", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://developers.asana.com/docs/", authUrl: "https://asana.com/create-account", contactUrl: "https://asana.com/support" },
  { serviceName: "monday-com", description: "Work OS platform API for project and workflow management", endpoint: "https://api.monday.com/v2", protocol: "GraphQL", capabilities: "boards, items, columns, groups, updates, automations, webhooks", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.monday.com/api-reference/docs", authUrl: "https://auth.monday.com/users/sign_up_new", contactUrl: "https://monday.com/helpcenter/contact-us" },
  { serviceName: "clickup", description: "Productivity platform API with tasks, docs, and goals", endpoint: "https://api.clickup.com/api/v2", protocol: "REST", capabilities: "tasks, spaces, folders, lists, goals, time tracking, views", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://clickup.com/api/", authUrl: "https://app.clickup.com/signup", contactUrl: "https://clickup.com/support" },
  { serviceName: "trello-api", description: "Kanban-style project management board API", endpoint: "https://api.trello.com/1", protocol: "REST", capabilities: "boards, lists, cards, checklists, labels, members, webhooks", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.atlassian.com/cloud/trello/rest/", authUrl: "https://trello.com/signup", contactUrl: "https://support.atlassian.com/trello/" },
  { serviceName: "basecamp-api", description: "Project management and team communication platform API", endpoint: "https://3.basecampapi.com", protocol: "REST", capabilities: "projects, to-dos, messages, campfires, schedules, documents", pricingModel: "subscription", authMethod: "OAuth2", docsUrl: "https://github.com/basecamp/bc3-api", authUrl: "https://basecamp.com/signup", contactUrl: "https://basecamp.com/support" },
  { serviceName: "shortcut", description: "Project management for software teams (formerly Clubhouse)", endpoint: "https://api.app.shortcut.com/api/v3", protocol: "REST", capabilities: "stories, epics, iterations, milestones, labels, workflows", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.shortcut.com/api/rest/v3", authUrl: "https://app.shortcut.com/signup", contactUrl: "https://shortcut.com/support" },

  // ─── 20. CRM ───────────────────────────────────────────────────────
  { serviceName: "salesforce-api", description: "Enterprise CRM platform with comprehensive REST and SOAP APIs", endpoint: "https://{instance}.salesforce.com/services/data/v59.0", protocol: "REST", capabilities: "accounts, contacts, leads, opportunities, reports, SOQL, bulk API", pricingModel: "subscription", authMethod: "OAuth2", docsUrl: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/", authUrl: "https://developer.salesforce.com/signup", contactUrl: "https://www.salesforce.com/company/contact-us/" },
  { serviceName: "hubspot-api", description: "CRM platform with marketing, sales, and service APIs", endpoint: "https://api.hubapi.com", protocol: "REST", capabilities: "contacts, companies, deals, tickets, marketing email, workflows", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://developers.hubspot.com/docs/api/overview", authUrl: "https://app.hubspot.com/signup/developers", contactUrl: "https://www.hubspot.com/contact-sales" },
  { serviceName: "pipedrive", description: "Sales CRM and pipeline management API for sales teams", endpoint: "https://api.pipedrive.com/v1", protocol: "REST", capabilities: "deals, persons, organizations, activities, pipelines, products", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://developers.pipedrive.com/docs/api/v1", authUrl: "https://www.pipedrive.com/en/register", contactUrl: "https://www.pipedrive.com/en/contact-us" },
  { serviceName: "zoho-crm", description: "CRM platform for sales automation and customer management", endpoint: "https://www.zohoapis.com/crm/v5", protocol: "REST", capabilities: "leads, contacts, deals, accounts, campaigns, analytics, blueprints", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://www.zoho.com/crm/developer/docs/api/v5/", authUrl: "https://www.zoho.com/crm/signup.html", contactUrl: "https://www.zoho.com/contactus.html" },
  { serviceName: "close-crm", description: "Sales CRM with built-in calling, email, and automation", endpoint: "https://api.close.com/api/v1", protocol: "REST", capabilities: "leads, contacts, activities, opportunities, sequences, smart views", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://developer.close.com/", authUrl: "https://app.close.com/signup/", contactUrl: "https://close.com/contact/" },
  { serviceName: "freshsales", description: "Sales CRM with AI-powered lead scoring and pipeline management", endpoint: "https://{domain}.myfreshworks.com/crm/sales/api", protocol: "REST", capabilities: "contacts, deals, accounts, tasks, appointments, sales sequences", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.freshworks.com/crm/api/", authUrl: "https://www.freshworks.com/crm/signup/", contactUrl: "https://www.freshworks.com/company/contact/" },

  // ─── 21. Security ──────────────────────────────────────────────────
  { serviceName: "snyk", description: "Developer security platform for code, dependencies, and containers", endpoint: "https://api.snyk.io/rest", protocol: "REST", capabilities: "vulnerability scanning, dependency analysis, container security, IaC scanning", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.snyk.io/snyk-api/", authUrl: "https://app.snyk.io/signup", contactUrl: "https://snyk.io/contact-us/" },
  { serviceName: "sonarcloud", description: "Cloud-based code quality and security analysis platform", endpoint: "https://sonarcloud.io/api", protocol: "REST", capabilities: "code analysis, security hotspots, quality gates, coverage, duplications", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://sonarcloud.io/web_api", authUrl: "https://sonarcloud.io/sessions/new", contactUrl: "https://community.sonarsource.com/" },
  { serviceName: "crowdstrike", description: "Endpoint security and threat intelligence platform", endpoint: "https://api.crowdstrike.com", protocol: "REST", capabilities: "threat detection, endpoint protection, threat intel, vulnerability management", pricingModel: "subscription", authMethod: "OAuth2", docsUrl: "https://falcon.crowdstrike.com/documentation/", authUrl: "https://www.crowdstrike.com/free-trial-guide/", contactUrl: "https://www.crowdstrike.com/contact-us/" },
  { serviceName: "hashicorp-vault", description: "Secrets management and data protection platform", endpoint: "https://{vault-addr}/v1", protocol: "REST", capabilities: "secrets management, encryption, PKI, dynamic credentials, identity", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://developer.hashicorp.com/vault/api-docs", authUrl: "https://portal.cloud.hashicorp.com/sign-up", contactUrl: "https://www.hashicorp.com/contact-sales" },
  { serviceName: "1password-connect", description: "Secrets automation API for 1Password vault access", endpoint: "https://{connect-server}/v1", protocol: "REST", capabilities: "vault access, item retrieval, secret injection, automation", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://developer.1password.com/docs/connect/", authUrl: "https://1password.com/sign-up/business/", contactUrl: "https://support.1password.com/contact/" },

  // ─── 22. Monitoring & Observability ────────────────────────────────
  { serviceName: "grafana-cloud", description: "Observability platform for metrics, logs, and traces", endpoint: "https://grafana.com/api", protocol: "REST", capabilities: "dashboards, alerting, metrics, logs, traces, Prometheus, Loki", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://grafana.com/docs/grafana-cloud/developer-resources/api-reference/", authUrl: "https://grafana.com/auth/sign-up/create-user", contactUrl: "https://grafana.com/contact" },
  { serviceName: "splunk", description: "Data platform for security and observability", endpoint: "https://{host}:8089/services", protocol: "REST", capabilities: "log management, SIEM, APM, infrastructure monitoring, SOAR", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTprolog", authUrl: "https://www.splunk.com/en_us/download.html", contactUrl: "https://www.splunk.com/en_us/about-splunk/contact-us.html" },
  { serviceName: "honeycomb", description: "Observability platform for distributed systems debugging", endpoint: "https://api.honeycomb.io/1", protocol: "REST", capabilities: "distributed tracing, events, queries, SLOs, BubbleUp analysis", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.honeycomb.io/api/", authUrl: "https://ui.honeycomb.io/signup", contactUrl: "https://www.honeycomb.io/contact-us" },
  { serviceName: "elastic-apm", description: "Application performance monitoring built on Elasticsearch", endpoint: "https://{deployment}.apm.{region}.cloud.es.io", protocol: "REST", capabilities: "distributed tracing, error tracking, metrics, service maps, anomaly detection", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.elastic.co/guide/en/apm/guide/current/index.html", authUrl: "https://cloud.elastic.co/registration", contactUrl: "https://www.elastic.co/contact" },
  { serviceName: "lightstep", description: "Observability platform for microservices (now ServiceNow)", endpoint: "https://api.lightstep.com/public/v0.2", protocol: "REST", capabilities: "distributed tracing, change intelligence, service health, SLOs", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.lightstep.com/docs/api-reference", authUrl: "https://app.lightstep.com/signup", contactUrl: "https://lightstep.com/contact-us" },
  { serviceName: "betterstack", description: "Uptime monitoring, on-call alerting, and log management", endpoint: "https://uptime.betterstack.com/api/v2", protocol: "REST", capabilities: "uptime monitoring, incidents, on-call, status pages, logs", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://betterstack.com/docs/uptime/api/", authUrl: "https://betterstack.com/users/sign-up", contactUrl: "https://betterstack.com/contact" },

  // ─── 23. Email Marketing ───────────────────────────────────────────
  { serviceName: "mailchimp", description: "Email marketing and automation platform API", endpoint: "https://{dc}.api.mailchimp.com/3.0", protocol: "REST", capabilities: "campaigns, audiences, automations, templates, reports, segments", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://mailchimp.com/developer/marketing/api/", authUrl: "https://login.mailchimp.com/signup/", contactUrl: "https://mailchimp.com/contact/" },
  { serviceName: "convertkit", description: "Email marketing platform for creators and bloggers", endpoint: "https://api.convertkit.com/v3", protocol: "REST", capabilities: "subscribers, forms, sequences, broadcasts, tags, automations", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.convertkit.com/", authUrl: "https://app.convertkit.com/users/signup", contactUrl: "https://convertkit.com/contact" },
  { serviceName: "beehiiv", description: "Newsletter platform for creators with growth tools", endpoint: "https://api.beehiiv.com/v2", protocol: "REST", capabilities: "publications, posts, subscriptions, segments, automations", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.beehiiv.com/docs/v2/", authUrl: "https://www.beehiiv.com/create", contactUrl: "https://www.beehiiv.com/support" },
  { serviceName: "campaign-monitor", description: "Email marketing platform with drag-and-drop design tools", endpoint: "https://api.createsend.com/api/v3.3", protocol: "REST", capabilities: "campaigns, lists, subscribers, templates, automations, transactional", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.campaignmonitor.com/api/v3.3/", authUrl: "https://www.campaignmonitor.com/signup/", contactUrl: "https://www.campaignmonitor.com/contact/" },
  { serviceName: "brevo", description: "Marketing platform with email, SMS, and chat automation", endpoint: "https://api.brevo.com/v3", protocol: "REST", capabilities: "email campaigns, SMS, WhatsApp, automation, contacts, transactional", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.brevo.com/reference/", authUrl: "https://app.brevo.com/account/register", contactUrl: "https://www.brevo.com/contact/" },
  { serviceName: "resend", description: "Email API for developers with React Email integration", endpoint: "https://api.resend.com", protocol: "REST", capabilities: "transactional email, domains, API keys, webhooks, React Email", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://resend.com/docs/api-reference/introduction", authUrl: "https://resend.com/signup", contactUrl: "https://resend.com/contact" },

  // ─── 24. Forms & Surveys ───────────────────────────────────────────
  { serviceName: "typeform", description: "Conversational forms and surveys with beautiful design", endpoint: "https://api.typeform.com", protocol: "REST", capabilities: "forms, responses, workspaces, themes, images, webhooks", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://www.typeform.com/developers/", authUrl: "https://admin.typeform.com/signup", contactUrl: "https://www.typeform.com/help/" },
  { serviceName: "jotform", description: "Online form builder with integrations and workflow automation", endpoint: "https://api.jotform.com", protocol: "REST", capabilities: "forms, submissions, reports, widgets, payments, approvals", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://api.jotform.com/docs/", authUrl: "https://www.jotform.com/signup/", contactUrl: "https://www.jotform.com/contact/" },
  { serviceName: "surveymonkey", description: "Survey platform for feedback, research, and data collection", endpoint: "https://api.surveymonkey.com/v3", protocol: "REST", capabilities: "surveys, responses, collectors, contacts, benchmarks, webhooks", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://developer.surveymonkey.com/api/v3/", authUrl: "https://developer.surveymonkey.com/apps/", contactUrl: "https://help.surveymonkey.com/en/contact/" },
  { serviceName: "tally-forms", description: "Simple and free form builder for creators", endpoint: "https://api.tally.so", protocol: "REST", capabilities: "forms, submissions, webhooks, conditional logic, file uploads", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://tally.so/help/developer-resources", authUrl: "https://tally.so/signup", contactUrl: "https://tally.so/help" },
  { serviceName: "formbricks", description: "Open-source survey and experience management platform", endpoint: "https://app.formbricks.com/api/v1", protocol: "REST", capabilities: "surveys, in-app surveys, link surveys, website surveys, feedback", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://formbricks.com/docs/api/overview", authUrl: "https://app.formbricks.com/auth/signup", contactUrl: "https://formbricks.com/contact" },

  // ─── 25. DNS & Domains ─────────────────────────────────────────────
  { serviceName: "cloudflare-dns", description: "Enterprise DNS with DDoS protection and global CDN", endpoint: "https://api.cloudflare.com/client/v4", protocol: "REST", capabilities: "DNS management, DNSSEC, load balancing, traffic steering, analytics", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.cloudflare.com/api/", authUrl: "https://dash.cloudflare.com/sign-up", contactUrl: "https://www.cloudflare.com/plans/enterprise/contact/" },
  { serviceName: "route53", description: "AWS scalable domain name system and health checking", endpoint: "https://route53.amazonaws.com/2013-04-01", protocol: "REST", capabilities: "DNS hosting, health checks, traffic routing, domain registration", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.aws.amazon.com/Route53/latest/APIReference/", authUrl: "https://aws.amazon.com/free/", contactUrl: "https://aws.amazon.com/contact-us/" },
  { serviceName: "namecheap-api", description: "Domain registration and management API", endpoint: "https://api.namecheap.com/xml.response", protocol: "REST", capabilities: "domain registration, DNS management, SSL, transfers, WHOIS", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.namecheap.com/support/api/intro/", authUrl: "https://www.namecheap.com/myaccount/signup/", contactUrl: "https://www.namecheap.com/support/" },
  { serviceName: "godaddy-api", description: "Domain registration, hosting, and website builder API", endpoint: "https://api.godaddy.com/v1", protocol: "REST", capabilities: "domains, DNS, certificates, aftermarket, abuse reporting", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://developer.godaddy.com/", authUrl: "https://sso.godaddy.com/v1/account/create", contactUrl: "https://www.godaddy.com/help" },
  { serviceName: "dnsimple", description: "DNS hosting and domain management API", endpoint: "https://api.dnsimple.com/v2", protocol: "REST", capabilities: "DNS management, domain registration, certificates, WHOIS privacy", pricingModel: "subscription", authMethod: "Bearer token", docsUrl: "https://developer.dnsimple.com/v2/", authUrl: "https://dnsimple.com/signup", contactUrl: "https://dnsimple.com/contact" },

  // ─── 26. Blockchain/Web3 ───────────────────────────────────────────
  { serviceName: "etherscan", description: "Ethereum blockchain explorer and analytics API", endpoint: "https://api.etherscan.io/api", protocol: "REST", capabilities: "transactions, balances, tokens, contracts, gas tracker, logs", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.etherscan.io/", authUrl: "https://etherscan.io/register", contactUrl: "https://etherscan.io/contactus" },
  { serviceName: "the-graph", description: "Decentralized indexing protocol for querying blockchain data", endpoint: "https://gateway.thegraph.com/api", protocol: "GraphQL", capabilities: "subgraphs, indexing, querying, DeFi data, NFT data, governance", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://thegraph.com/docs/en/", authUrl: "https://thegraph.com/studio/", contactUrl: "https://thegraph.com/ecosystem/about/" },
  { serviceName: "opensea-api", description: "NFT marketplace API for collections, assets, and orders", endpoint: "https://api.opensea.io/api/v2", protocol: "REST", capabilities: "NFT listings, collections, offers, traits, events, account data", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.opensea.io/reference/api-overview", authUrl: "https://opensea.io/account/settings", contactUrl: "https://support.opensea.io/hc/en-us" },
  { serviceName: "pinata-ipfs", description: "IPFS pinning service for decentralized file storage", endpoint: "https://api.pinata.cloud", protocol: "REST", capabilities: "IPFS pinning, file upload, dedicated gateways, Submarine, groups", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.pinata.cloud/", authUrl: "https://app.pinata.cloud/register", contactUrl: "https://www.pinata.cloud/contact" },
  { serviceName: "chainlink", description: "Decentralized oracle network for blockchain data feeds", endpoint: "https://chain.link/data-feeds", protocol: "REST", capabilities: "price feeds, VRF, automation, CCIP, functions, data streams", pricingModel: "per-request", authMethod: "none", docsUrl: "https://docs.chain.link/", authUrl: "https://chain.link/", contactUrl: "https://chain.link/contact" },

  // ─── 27. Testing ───────────────────────────────────────────────────
  { serviceName: "browserstack", description: "Cross-browser testing and mobile app testing cloud platform", endpoint: "https://api.browserstack.com", protocol: "REST", capabilities: "live testing, automated testing, app testing, accessibility, visual testing", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://www.browserstack.com/docs/", authUrl: "https://www.browserstack.com/users/sign_up", contactUrl: "https://www.browserstack.com/contact" },
  { serviceName: "sauce-labs", description: "Cloud testing platform for web and mobile applications", endpoint: "https://api.us-west-1.saucelabs.com/rest/v1", protocol: "REST", capabilities: "automated testing, live testing, API testing, error reporting, analytics", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://docs.saucelabs.com/dev/api/", authUrl: "https://saucelabs.com/sign-up", contactUrl: "https://saucelabs.com/contact" },
  { serviceName: "lambdatest", description: "Cross-browser and cross-platform testing cloud", endpoint: "https://api.lambdatest.com/automation/api/v1", protocol: "REST", capabilities: "browser testing, mobile testing, real-time testing, visual regression", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.lambdatest.com/support/api-doc/", authUrl: "https://accounts.lambdatest.com/register", contactUrl: "https://www.lambdatest.com/contact-us" },
  { serviceName: "percy", description: "Visual testing and review platform for UI changes", endpoint: "https://percy.io/api/v1", protocol: "REST", capabilities: "visual snapshots, visual diffs, review workflows, browser coverage", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://www.browserstack.com/docs/percy/", authUrl: "https://percy.io/signup", contactUrl: "https://www.browserstack.com/contact" },
  { serviceName: "chromatic", description: "Visual testing platform for Storybook component libraries", endpoint: "https://www.chromatic.com/api", protocol: "REST", capabilities: "visual regression testing, UI review, Storybook publishing, interaction testing", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.chromatic.com/docs/", authUrl: "https://www.chromatic.com/start", contactUrl: "https://www.chromatic.com/contact" },

  // ─── 28. Shipping & Logistics ──────────────────────────────────────
  { serviceName: "shipengine", description: "Shipping API for rates, labels, and tracking across carriers", endpoint: "https://api.shipengine.com/v1", protocol: "REST", capabilities: "rates, labels, tracking, address validation, carrier accounts", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://shipengine.github.io/shipengine-openapi/", authUrl: "https://www.shipengine.com/signup/", contactUrl: "https://www.shipengine.com/contact/" },
  { serviceName: "easypost", description: "Shipping API for e-commerce with multi-carrier support", endpoint: "https://api.easypost.com/v2", protocol: "REST", capabilities: "shipping rates, labels, tracking, address verification, insurance", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.easypost.com/", authUrl: "https://www.easypost.com/signup", contactUrl: "https://www.easypost.com/contact" },
  { serviceName: "shippo", description: "Multi-carrier shipping API for rates, labels, and tracking", endpoint: "https://api.goshippo.com", protocol: "REST", capabilities: "shipping rates, labels, tracking, customs, batch shipping", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.goshippo.com/", authUrl: "https://apps.goshippo.com/join", contactUrl: "https://goshippo.com/contact" },
  { serviceName: "aftership", description: "Shipment tracking and delivery experience platform", endpoint: "https://api.aftership.com/v4", protocol: "REST", capabilities: "shipment tracking, notifications, estimated delivery, analytics", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.aftership.com/docs/tracking/overview", authUrl: "https://accounts.aftership.com/signup", contactUrl: "https://www.aftership.com/contact-us" },
  { serviceName: "flexport", description: "Freight forwarding and supply chain logistics platform", endpoint: "https://api.flexport.com/v2", protocol: "REST", capabilities: "shipments, bookings, documents, tracking, commercial invoices", pricingModel: "contact", authMethod: "API key", docsUrl: "https://apidocs.flexport.com/", authUrl: "https://www.flexport.com/signup", contactUrl: "https://www.flexport.com/contact" },

  // ─── 29. Notification ──────────────────────────────────────────────
  { serviceName: "onesignal", description: "Multi-channel notification delivery platform", endpoint: "https://onesignal.com/api/v1", protocol: "REST", capabilities: "push notifications, email, SMS, in-app messaging, segments", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://documentation.onesignal.com/reference/", authUrl: "https://app.onesignal.com/signup", contactUrl: "https://onesignal.com/contact" },
  { serviceName: "pusher", description: "Real-time messaging and notification infrastructure", endpoint: "https://api-{cluster}.pusher.com", protocol: "REST", capabilities: "channels, presence, events, triggers, webhooks, end-to-end encryption", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://pusher.com/docs/channels/server_api/overview/", authUrl: "https://dashboard.pusher.com/accounts/sign_up", contactUrl: "https://pusher.com/support" },
  { serviceName: "ably", description: "Real-time messaging and pub/sub platform for developers", endpoint: "https://rest.ably.io", protocol: "REST", capabilities: "pub/sub, presence, history, push notifications, SSE, MQTT", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://ably.com/docs/api/rest-api", authUrl: "https://ably.com/sign-up", contactUrl: "https://ably.com/contact" },
  { serviceName: "firebase-cloud-messaging", description: "Cross-platform push notification delivery from Google", endpoint: "https://fcm.googleapis.com/v1", protocol: "REST", capabilities: "push notifications, topics, device groups, analytics, A/B testing", pricingModel: "free", authMethod: "OAuth2", docsUrl: "https://firebase.google.com/docs/cloud-messaging", authUrl: "https://console.firebase.google.com/", contactUrl: "https://firebase.google.com/support" },
  { serviceName: "amazon-sns", description: "AWS managed pub/sub messaging and notification service", endpoint: "https://sns.{region}.amazonaws.com", protocol: "REST", capabilities: "pub/sub, SMS, push notifications, email, HTTP delivery, FIFO", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.aws.amazon.com/sns/latest/api/", authUrl: "https://aws.amazon.com/free/", contactUrl: "https://aws.amazon.com/contact-us/" },
  { serviceName: "knock", description: "Notification infrastructure for product teams", endpoint: "https://api.knock.app/v1", protocol: "REST", capabilities: "workflows, channels, preferences, batching, schedules, feeds", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.knock.app/reference", authUrl: "https://dashboard.knock.app/signup", contactUrl: "https://knock.app/contact" },
  { serviceName: "novu", description: "Open-source notification infrastructure for developers", endpoint: "https://api.novu.co/v1", protocol: "REST", capabilities: "notification workflows, multi-channel, preferences, digest, templates", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.novu.co/api-reference/overview", authUrl: "https://web.novu.co/auth/signup", contactUrl: "https://novu.co/contact-us" },

  // ─── 30. Search ────────────────────────────────────────────────────
  { serviceName: "meilisearch", description: "Lightning-fast open-source search engine with typo tolerance", endpoint: "https://cloud.meilisearch.com", protocol: "REST", capabilities: "full-text search, typo tolerance, filtering, faceting, geo search", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.meilisearch.com/docs", authUrl: "https://cloud.meilisearch.com/register", contactUrl: "https://www.meilisearch.com/contact" },
  { serviceName: "typesense", description: "Open-source search engine optimized for instant search", endpoint: "https://{cluster}.a1.typesense.net", protocol: "REST", capabilities: "full-text search, faceting, filtering, geo search, vector search", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://typesense.org/docs/", authUrl: "https://cloud.typesense.org/signup", contactUrl: "https://typesense.org/contact/" },
  { serviceName: "swiftype", description: "Elasticsearch-powered site search and enterprise search", endpoint: "https://api.swiftype.com/api/v1", protocol: "REST", capabilities: "site search, enterprise search, crawling, analytics, relevance tuning", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://swiftype.com/documentation", authUrl: "https://app.swiftype.com/signup", contactUrl: "https://swiftype.com/contact" },
  { serviceName: "coveo", description: "AI-powered search and recommendations platform", endpoint: "https://platform.cloud.coveo.com/rest/search/v2", protocol: "REST", capabilities: "search, recommendations, personalization, analytics, ML relevance", pricingModel: "contact", authMethod: "Bearer token", docsUrl: "https://docs.coveo.com/en/13/api-reference", authUrl: "https://www.coveo.com/en/free-trial", contactUrl: "https://www.coveo.com/en/contact" },
  { serviceName: "algolia", description: "AI-powered search and discovery API", endpoint: "https://{application-id}.algolia.net/1", protocol: "REST", capabilities: "full-text search, faceting, analytics, A/B testing, recommendations", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.algolia.com/doc/", authUrl: "https://www.algolia.com/users/sign_up", contactUrl: "https://www.algolia.com/contact/" },

  // ─── BONUS: Additional services to hit 200+ ────────────────────────

  // Payments/Billing extras
  { serviceName: "lemonsqueezy", description: "Payments and billing platform for SaaS and digital products", endpoint: "https://api.lemonsqueezy.com/v1", protocol: "REST", capabilities: "subscriptions, checkouts, products, license keys, webhooks", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://docs.lemonsqueezy.com/api", authUrl: "https://app.lemonsqueezy.com/register", contactUrl: "https://www.lemonsqueezy.com/contact" },
  { serviceName: "paddle", description: "Payment infrastructure for SaaS and subscription billing", endpoint: "https://api.paddle.com", protocol: "REST", capabilities: "subscriptions, checkouts, pricing, invoicing, tax compliance", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://developer.paddle.com/api-reference/overview", authUrl: "https://login.paddle.com/signup", contactUrl: "https://www.paddle.com/contact-us" },
  { serviceName: "chargebee", description: "Subscription billing and revenue management platform", endpoint: "https://{site}.chargebee.com/api/v2", protocol: "REST", capabilities: "subscriptions, invoicing, payments, dunning, revenue recognition", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://apidocs.chargebee.com/docs/api/", authUrl: "https://www.chargebee.com/trial-signup/", contactUrl: "https://www.chargebee.com/company/contact/" },

  // Feature Flags
  { serviceName: "launchdarkly", description: "Feature management platform with progressive delivery", endpoint: "https://app.launchdarkly.com/api/v2", protocol: "REST", capabilities: "feature flags, targeting, experimentation, progressive rollouts", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://apidocs.launchdarkly.com/", authUrl: "https://app.launchdarkly.com/signup", contactUrl: "https://launchdarkly.com/contact-us/" },
  { serviceName: "statsig", description: "Feature flags, experiments, and product analytics platform", endpoint: "https://statsigapi.net/console/v1", protocol: "REST", capabilities: "feature gates, experiments, dynamic config, metrics, holdouts", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.statsig.com/console-api/introduction", authUrl: "https://www.statsig.com/signup", contactUrl: "https://www.statsig.com/contact" },

  // Error & Log management
  { serviceName: "logrocket", description: "Session replay and error tracking for frontend apps", endpoint: "https://api.logrocket.com/v1", protocol: "REST", capabilities: "session replay, error tracking, performance monitoring, product analytics", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.logrocket.com/reference/", authUrl: "https://app.logrocket.com/signup/", contactUrl: "https://logrocket.com/contact-us" },
  { serviceName: "bugsnag", description: "Application stability management and error monitoring", endpoint: "https://api.bugsnag.com", protocol: "REST", capabilities: "error monitoring, stability tracking, release health, breadcrumbs", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://bugsnagapiv2.docs.apiary.io/", authUrl: "https://app.bugsnag.com/user/new", contactUrl: "https://www.bugsnag.com/contact/" },

  // Low-code/Automation
  { serviceName: "n8n", description: "Open-source workflow automation with code flexibility", endpoint: "https://{instance}.app.n8n.cloud/api/v1", protocol: "REST", capabilities: "workflows, triggers, credentials, executions, variables, webhooks", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.n8n.io/api/", authUrl: "https://app.n8n.cloud/register", contactUrl: "https://n8n.io/contact" },
  { serviceName: "pipedream", description: "Integration platform for developers with code-level control", endpoint: "https://api.pipedream.com/v1", protocol: "REST", capabilities: "workflows, event sources, connected accounts, data stores", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://pipedream.com/docs/api/", authUrl: "https://pipedream.com/auth/signup", contactUrl: "https://pipedream.com/support" },

  // AI Image Generation
  { serviceName: "midjourney", description: "AI image generation service for creative visuals", endpoint: "https://api.midjourney.com", protocol: "REST", capabilities: "image generation, variations, upscaling, style transfer", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://docs.midjourney.com/", authUrl: "https://www.midjourney.com/", contactUrl: "https://www.midjourney.com/support" },
  { serviceName: "leonardo-ai", description: "AI image generation platform with fine-tuned models", endpoint: "https://cloud.leonardo.ai/api/rest/v1", protocol: "REST", capabilities: "image generation, model training, canvas editing, texture generation", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.leonardo.ai/reference", authUrl: "https://app.leonardo.ai/auth/login", contactUrl: "https://leonardo.ai/contact" },
  { serviceName: "ideogram", description: "AI image generation with exceptional text rendering", endpoint: "https://api.ideogram.ai", protocol: "REST", capabilities: "image generation, text rendering, editing, style mixing", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developer.ideogram.ai/api-reference", authUrl: "https://ideogram.ai/login", contactUrl: "https://ideogram.ai/contact" },

  // Database tools
  { serviceName: "hasura", description: "Instant GraphQL and REST APIs on databases", endpoint: "https://{project}.hasura.app/v1/graphql", protocol: "GraphQL", capabilities: "instant APIs, subscriptions, authorization, event triggers, remote schemas", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://hasura.io/docs/latest/api-reference/", authUrl: "https://cloud.hasura.io/signup", contactUrl: "https://hasura.io/contact-us/" },
  { serviceName: "prisma-accelerate", description: "Global database cache and connection pooling for Prisma", endpoint: "https://accelerate.prisma-data.net", protocol: "REST", capabilities: "connection pooling, global caching, query optimization, edge access", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://www.prisma.io/docs/accelerate", authUrl: "https://console.prisma.io/", contactUrl: "https://www.prisma.io/contact" },

  // Customer support
  { serviceName: "zendesk-api", description: "Customer service and engagement platform API", endpoint: "https://{subdomain}.zendesk.com/api/v2", protocol: "REST", capabilities: "tickets, users, organizations, search, talk, chat, guide", pricingModel: "subscription", authMethod: "API key", docsUrl: "https://developer.zendesk.com/api-reference/", authUrl: "https://www.zendesk.com/register/", contactUrl: "https://www.zendesk.com/contact/" },
  { serviceName: "freshdesk", description: "Customer support and helpdesk platform API", endpoint: "https://{domain}.freshdesk.com/api/v2", protocol: "REST", capabilities: "tickets, contacts, agents, automations, knowledge base, forums", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://developers.freshdesk.com/api/", authUrl: "https://freshdesk.com/signup", contactUrl: "https://www.freshworks.com/company/contact/" },

  // Code/Dev extras
  { serviceName: "gitlab-api", description: "DevOps platform API for repositories, CI/CD, and project management", endpoint: "https://gitlab.com/api/v4", protocol: "REST", capabilities: "repositories, CI/CD, merge requests, issues, packages, registry", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://docs.gitlab.com/ee/api/rest/", authUrl: "https://gitlab.com/users/sign_up", contactUrl: "https://about.gitlab.com/sales/" },
  { serviceName: "bitbucket-api", description: "Atlassian code hosting and CI/CD platform API", endpoint: "https://api.bitbucket.org/2.0", protocol: "REST", capabilities: "repositories, pull requests, pipelines, snippets, deployments", pricingModel: "tiered", authMethod: "OAuth2", docsUrl: "https://developer.atlassian.com/cloud/bitbucket/rest/intro/", authUrl: "https://bitbucket.org/account/signup/", contactUrl: "https://support.atlassian.com/bitbucket-cloud/" },
  { serviceName: "snyk-container", description: "Container and Kubernetes security scanning", endpoint: "https://api.snyk.io/rest", protocol: "REST", capabilities: "container scanning, base image recommendations, Kubernetes monitoring", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.snyk.io/scan-with-snyk/snyk-container", authUrl: "https://app.snyk.io/signup", contactUrl: "https://snyk.io/contact-us/" },

  // Misc useful APIs
  { serviceName: "twilio-verify", description: "Phone verification and two-factor authentication API", endpoint: "https://verify.twilio.com/v2", protocol: "REST", capabilities: "SMS verification, voice verification, email verification, push verification", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://www.twilio.com/docs/verify/api", authUrl: "https://www.twilio.com/try-twilio", contactUrl: "https://www.twilio.com/help/contact" },
  { serviceName: "abstract-api", description: "Suite of utility APIs for validation and enrichment", endpoint: "https://emailvalidation.abstractapi.com/v1", protocol: "REST", capabilities: "email validation, IP geolocation, phone validation, VAT, holidays", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://docs.abstractapi.com/", authUrl: "https://app.abstractapi.com/users/signup", contactUrl: "https://www.abstractapi.com/contact-us" },
  { serviceName: "clearbit", description: "Business intelligence APIs for enrichment and prospecting", endpoint: "https://person.clearbit.com/v2", protocol: "REST", capabilities: "person enrichment, company enrichment, prospecting, reveal, risk", pricingModel: "contact", authMethod: "API key", docsUrl: "https://dashboard.clearbit.com/docs", authUrl: "https://dashboard.clearbit.com/signup", contactUrl: "https://clearbit.com/contact" },
  { serviceName: "hunter-io", description: "Email finder and verification API for outreach", endpoint: "https://api.hunter.io/v2", protocol: "REST", capabilities: "email finder, email verifier, domain search, lead generation", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://hunter.io/api-documentation/v2", authUrl: "https://hunter.io/users/sign_up", contactUrl: "https://hunter.io/contact" },
  { serviceName: "screenshotone", description: "Website screenshot and rendering API", endpoint: "https://api.screenshotone.com/take", protocol: "REST", capabilities: "screenshots, full page, PDF rendering, animations, selectors", pricingModel: "tiered", authMethod: "API key", docsUrl: "https://screenshotone.com/docs/getting-started/", authUrl: "https://screenshotone.com/sign-up", contactUrl: "https://screenshotone.com/contacts/" },
  { serviceName: "openai-whisper", description: "OpenAI speech-to-text API powered by Whisper model", endpoint: "https://api.openai.com/v1/audio", protocol: "REST", capabilities: "transcription, translation, timestamp generation, word-level timing", pricingModel: "per-request", authMethod: "API key", docsUrl: "https://platform.openai.com/docs/guides/speech-to-text", authUrl: "https://platform.openai.com/signup", contactUrl: "https://help.openai.com/en/" },
  { serviceName: "vercel-ai-sdk", description: "Vercel AI SDK for building AI-powered applications", endpoint: "https://api.vercel.com/v1", protocol: "REST", capabilities: "AI gateway, model routing, streaming, tool calling, structured output", pricingModel: "tiered", authMethod: "Bearer token", docsUrl: "https://sdk.vercel.ai/docs", authUrl: "https://vercel.com/signup", contactUrl: "https://vercel.com/contact" },
];

async function seed() {
  console.log(`\nSeeding ${services.length} new services to AgentDoor...\n`);
  let success = 0;
  let failed = 0;
  let errors = [];

  // Batch in groups of 10 with 500ms delay
  for (let i = 0; i < services.length; i += 10) {
    const batch = services.slice(i, i + 10);
    const batchNum = Math.floor(i / 10) + 1;
    const totalBatches = Math.ceil(services.length / 10);

    const results = await Promise.allSettled(
      batch.map(svc =>
        fetch(REGISTER_URL, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(svc),
        }).then(r => r.json())
      )
    );

    for (let j = 0; j < results.length; j++) {
      const r = results[j];
      if (r.status === "fulfilled" && (r.value.ok || r.value.id || r.value.success)) {
        success++;
      } else {
        failed++;
        const name = batch[j]?.serviceName || "unknown";
        const reason = r.status === "rejected" ? r.reason?.message : JSON.stringify(r.value);
        errors.push(`  ${name}: ${reason}`);
      }
    }

    console.log(`  Batch ${batchNum}/${totalBatches}: ${batch.map(s => s.serviceName).join(", ")}`);
    console.log(`  Running total: ${success} registered, ${failed} failed\n`);

    // 500ms delay between batches
    if (i + 10 < services.length) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }

  // Summary
  console.log("═".repeat(60));
  console.log(`  COMPLETE: ${success} registered, ${failed} failed out of ${services.length}`);
  if (errors.length > 0) {
    console.log(`\n  Errors:`);
    errors.forEach(e => console.log(e));
  }
  console.log("═".repeat(60));

  // Check final count
  try {
    const stats = await fetch("https://api.agentdoor.ai/stats").then(r => r.json());
    console.log(`\n  Total services now indexed: ${stats.count}`);
  } catch (e) {
    console.log(`\n  (Could not fetch stats: ${e.message})`);
  }
}

seed();
